export const ja = {
  chat: "チャット",
  agents: "アシスタント設定",
  memory: "Memory",
  skills: "Skills",
  settings: "設定",
  newChat: "新しいチャット",
  send: "送信",
  stop: "停止",
  save: "保存",
  cancel: "キャンセル",
  confirm: "確定",
  approve: "確認",
  logout: "ログアウト",
  thinking: "Thinking",
  agent: "Agent",
  loading: "読み込み中…",
  communicationFailed: "通信に失敗しました",
  operationFailed: "処理に失敗しました",
  requestTimeout: "リクエストがタイムアウトしました",
  requestInterrupted: "リクエストを中断しました",
  streamLost: "ストリーム接続が切れました。状態は自動更新しています。",
};